unit TestUNorwegianBlue;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, UNorwegianBlue, UBird;

type
  // Test methods for class TNorwegianBlue

  TestTNorwegianBlue = class(TTestCase)
  strict private
    FNorwegianBlue: TNorwegianBlue;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestgetSpeed;
  end;

implementation

procedure TestTNorwegianBlue.SetUp;
begin
  FNorwegianBlue := TNorwegianBlue.Create;
end;

procedure TestTNorwegianBlue.TearDown;
begin
  FNorwegianBlue.Free;
  FNorwegianBlue := nil;
end;

procedure TestTNorwegianBlue.TestgetSpeed;
var
  ReturnValue: string;
begin
  ReturnValue := FNorwegianBlue.getSpeed;
  CheckEquals(ReturnValue, 'NorwegianBlue', 'сообщение об ошибке');
  // TODO: Validate method results
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTNorwegianBlue.Suite);
end.

