unit TestUBird;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit
  being tested.

}

interface

uses
  TestFramework, UBird, UEuropean, UAfrican, UNorwegianBlue;

type
  // Test methods for class TBird

  TestTBird = class(TTestCase)
  strict private
    FBird: TBird;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestgetSpeed;
    procedure TestgetSpeed1;
    procedure TestgetSpeed2;
  end;

implementation

procedure TestTBird.SetUp;
begin
  // FBird := TBird.Create;
end;

procedure TestTBird.TearDown;
begin
  FBird.Free;
  FBird := nil;
end;

procedure TestTBird.TestgetSpeed;
var
  ReturnValue: string;
begin
  FBird := TEuropean.Create;
  ReturnValue := FBird.getSpeed;
  CheckEquals(ReturnValue, 'European', 'сообщение об ошибке');
end;

procedure TestTBird.TestgetSpeed1;
var
  ReturnValue: string;
begin
  FBird := TAfrican.Create;
  ReturnValue := FBird.getSpeed;
  CheckEquals(ReturnValue, 'African', 'сообщение об ошибке');
end;

procedure TestTBird.TestgetSpeed2;
var
  ReturnValue: string;
begin
  FBird := TNorwegianBlue.Create;
  ReturnValue := FBird.getSpeed;
  CheckEquals(ReturnValue, 'NorwegianBlue', 'сообщение об ошибке');
end;

initialization

// Register any test cases with the test runner
RegisterTest(TestTBird.Suite);

end.
